# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('core', '0002_auto_20180302_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_url_root', models.URLField(help_text="Root URL of this site's LMS (e.g. https://courses.stage.edx.org)", verbose_name='LMS base url')),
                ('oauth_settings', jsonfield.fields.JSONField(default={}, help_text='JSON string containing OAuth backend settings.', verbose_name='OAuth settings')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
        ),
    ]
