# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='lms_public_url_root_override',
            field=models.URLField(blank=True, help_text="Root public URL of this site's LMS. Only used for overwriting client-side URLs", null=True, verbose_name='LMS public base url'),
        ),
    ]
