# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_lms_public_url_root_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='discovery_api_url',
            field=models.URLField(default='', verbose_name='Discovery API URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ecommerce_api_url',
            field=models.URLField(default='', verbose_name='Ecommerce API URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ecommerce_public_url_root',
            field=models.URLField(blank=True, null=True, verbose_name='Ecommerce public base url'),
        ),
    ]
