# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180328_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='discovery_journal_api_url',
            field=models.URLField(default='', verbose_name='Discovery API URL for Journal Endpoint'),
            preserve_default=False,
        ),
    ]
