# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_discovery_journal_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Header/Footer Logo'),
        ),
    ]
