# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180330_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='ecommerce_journal_api_url',
            field=models.URLField(default='', verbose_name='Ecommerce API URL for Journal Endpoint'),
            preserve_default=False,
        ),
    ]
