# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfiguration_ecommerce_journal_api_url'),
        ('core', '0007_siteconfiguration_site_logo'),
    ]

    operations = [
    ]
