# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20180405_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='discovery_partner_id',
            field=models.CharField(help_text='The short code of the associated Partner in discovery service (core_partners table)', max_length=8, verbose_name='Discovery service partner short code'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='ecommerce_partner_id',
            field=models.CharField(help_text='The short code of the associated Partner in ecommerce service (partner_partners table)', max_length=8, verbose_name='Ecommerce sevice partner short code'),
        ),
    ]
