# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180410_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_logo',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='oauth_settings',
            field=jsonfield.fields.JSONField(default={'SOCIAL_AUTH_EDX_OIDC_ID_TOKEN_DECRYPTION_KEY': '', 'SOCIAL_AUTH_EDX_OIDC_ISSUER': '', 'SOCIAL_AUTH_EDX_OIDC_ISSUERS': [''], 'SOCIAL_AUTH_EDX_OIDC_KEY': '', 'SOCIAL_AUTH_EDX_OIDC_LOGOUT_URL': '', 'SOCIAL_AUTH_EDX_OIDC_PUBLIC_URL_ROOT': '', 'SOCIAL_AUTH_EDX_OIDC_SECRET': '', 'SOCIAL_AUTH_EDX_OIDC_URL_ROOT': ''}, help_text='JSON string containing OAuth backend settings.', verbose_name='OAuth settings'),
        ),
    ]
