# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180511_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='frontend_url',
            field=models.URLField(default='http://localhost:1991', help_text='Root URL of frontend app for specific site (e.g. https://journalapp.edx.org)', verbose_name='Frontend app base url'),
            preserve_default=False,
        ),
    ]
