# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180718_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='segment_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
