# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_siteconfiguration_segment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='from_email',
            field=models.EmailField(default='journals@edx.org', max_length=254, verbose_name='From email address used in the system generated emails'),
        ),
    ]
