# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebranding',
            name='site_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journals.JournalImage'),
        ),
    ]
