# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20180327_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='access_length',
            field=models.DurationField(default=datetime.timedelta(days=365)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalaccess',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 1)),
            preserve_default=False,
        ),
    ]
