# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_auto_20180323_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='journals.Organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together=set([('name', 'organization')]),
        ),
    ]
