# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('journals', '0006_auto_20180330_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalindexpage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
