# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_journalindexpage_hero_image'),
        ('journals', '0005_auto_20180330_2156'),
    ]

    operations = [
    ]
