# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('journals', '0008_auto_20180405_1438'), ('journals', '0009_auto_20180405_1438')]

    dependencies = [
        ('journals', '0007_journalindexpage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaboutpage',
            name='card_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='journalaboutpage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='journalindexpage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
