# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_merge_20180405_1433'),
        ('journals', '0008_auto_20180405_1438_squashed_0009_auto_20180405_1438'),
    ]

    operations = [
    ]
