# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import journals.apps.journals.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_auto_20180405_1438_squashed_0009_auto_20180405_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='primary_source_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_source_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('rich_text', journals.apps.journals.blocks.JournalRichTextBlock(features=['h1', 'h2', 'h3', 'ol', 'ul', 'bold', 'italic', 'link', 'hr', 'document-link', 'image'])), ('image', journals.apps.journals.blocks.JournalImageChooserBlock()), ('pdf', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())))), ('xblock_video', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('video', journals.apps.journals.blocks.VideoChooserBlock(required=True)))))), blank=True),
        ),
    ]
