# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_auto_20180406_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='primary_source_url',
            new_name='fallback_source_url',
        ),
    ]
