# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 18:16
from __future__ import unicode_literals

from django.db import migrations
import journals.apps.journals.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_auto_20180405_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpage',
            name='body',
            field=wagtail.core.fields.StreamField((('rich_text', journals.apps.journals.blocks.JournalRichTextBlock(features=['h1', 'h2', 'h3', 'ol', 'ul', 'bold', 'italic', 'link', 'hr', 'document-link', 'image'])), ('image', journals.apps.journals.blocks.JournalImageChooserBlock()), ('pdf', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock()), ('doc', wagtail.documents.blocks.DocumentChooserBlock())))), ('xblock_video', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('video', journals.apps.journals.blocks.VideoChooserBlock(required=True)))))), blank=True),
        ),
    ]
