# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_auto_20180507_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaccess',
            name='order_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='journalaccess',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalaccess',
            name='revoked_date',
            field=models.DateField(null=True),
        ),
    ]
