# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import journals.apps.journals.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0012_auto_20180523_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='access_length',
            field=models.IntegerField(default=365, help_text='number of days valid after purchase', null=True),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('rich_text', journals.apps.journals.blocks.JournalRichTextBlock(features=['h1', 'h2', 'h3', 'ol', 'ul', 'bold', 'italic', 'link', 'hr', 'document-link', 'image'])), ('raw_html', journals.apps.journals.blocks.JournalRawHTMLBlock()), ('image', journals.apps.journals.blocks.JournalImageChooserBlock()), ('pdf', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock()), ('doc', wagtail.wagtaildocs.blocks.DocumentChooserBlock())))), ('xblock_video', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('video', journals.apps.journals.blocks.VideoChooserBlock(required=True)))))), blank=True),
        ),
    ]
