# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0016_journalpage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpagevisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
