# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-23 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0017_auto_20180718_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='journal_about_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_pages', to='journals.JournalAboutPage'),
        ),
    ]
