# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0017_auto_20180718_1531'),
        ('journals', '0018_auto_20180723_1409'),
    ]

    operations = [
    ]
