# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-24 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0018_journalpage_journal_about_page'),
        ('journals', '0019_merge_20180724_1349'),
    ]

    operations = [
    ]
