# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0021_auto_20180815_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
