# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0022_journalpage_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
