# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-17 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0023_journalpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='display_last_modified_date',
            field=models.BooleanField(default=False),
        ),
    ]
